### ISSUE TITLE
【依頼】ProtoSpace挙動確認

### ISSUE THREAD

**Issue by MasatakaTsuji** [MasatakaTsuji/protospace-30500#1]
自身のProtoSpaceのURL 
本番環境(Heroku)のURL  https://protospace-30500.herokuapp.com/

**Comment by vesper1102609** [comment]
ご提出ありがとうございます！
挙動確認させて頂いたところ、以下の不備が見受けられましたので修正をお願いします！
再提出お待ちしております。
またissueはLGTMが出るまでcloseなさらないようお願いいたします。
修正し次第、以下のprotospace完了報告フォームを再度提出お願いします！
※新しいissueを作っていただく必要はありません
https://forms.gle/ZdLeprTTWhMA8aZA7

**[修正箇所]**
**・空コメントで投稿ボタンを押すと詳細画面に戻らずエラーが発生します。**
空コメントで投稿した場合は、コメントが保存されず、且つ詳細ページに戻ってくるよう修正をお願いいたします。
![image](https://user-images.githubusercontent.com/49742444/96222123-a1f41000-0fc6-11eb-93cb-876d0ada0ee7.png)
![image](https://user-images.githubusercontent.com/49742444/96222129-a4ef0080-0fc6-11eb-8172-fb1645fb1ccc.png)


**・詳細ページからを削除をクリックしても、プロトタイプが削除できない時があります。**
コメントのない投稿は正常に削除できます。
しかしコメント投稿がされているプロトタイプを詳細画面から削除しようとするとエラーが発生するので、修正をお願いいたします。
![image](https://user-images.githubusercontent.com/49742444/96222207-cb14a080-0fc6-11eb-8c71-3767d89a8fce.png)

![image](https://user-images.githubusercontent.com/49742444/96222215-ce0f9100-0fc6-11eb-9c05-b37d9c9d0256.png)

![image](https://user-images.githubusercontent.com/49742444/96222225-d2d44500-0fc6-11eb-8763-5c371ca12c60.png)

**Comment by MasatakaTsuji** [comment]
訂正しました。
コメントを空欄で送るエラーを解決しました。
再度ご確認お願いします。

**Comment by MoonMaker23** [comment]
ご提出ありがとうございます！
挙動確認させて頂きましたが、全く問題ございませんでしたのでLGTMとさせて頂きます🎉
おめでとうございます！

別途、最終課題の案内をチャンネルの方に送信させて頂きます。
今しばらくお待ちください。
